-- E-commerce Store Database Schema

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `ecommerce_store` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce_store` ;

-- CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `ZIPCODE` VARCHAR(45) NOT NULL,
  `PHONE_NUMBER` VARCHAR(15) NOT NULL,
  `CUSTOMER_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE INDEX `CUSTOMER_EMAIL_UNIQUE` (`CUSTOMER_EMAIL`),
  UNIQUE INDEX `PHONE_NUMBER_UNIQUE` (`PHONE_NUMBER`)
) ENGINE = InnoDB;

-- PRODUCT TABLE
CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(200) NOT NULL,
  `PRODUCT_TYPE` VARCHAR(100) NOT NULL,
  `PRICE` DECIMAL(10,2) NOT NULL,
  `QUANTITY` INT NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE = InnoDB;

-- PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS `PAYMENTS` (
  `PAYMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `PAYMENT_TYPE` VARCHAR(45) NOT NULL,
  `CREDIT_CARD_NUMBER` CHAR(16) NOT NULL,
  `EXPIRY_DATE` DATE NOT NULL,
  `CVV` CHAR(4) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  INDEX `CUSTOMER_ID_FK1_idx` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_ID_FK1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- ORDERS TABLE
CREATE TABLE IF NOT EXISTS `ORDERS` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `DEVICE` VARCHAR(45) NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `PAYMENT_ID` INT NOT NULL,
  `SHIPPING_ADDRESS` VARCHAR(100) NOT NULL,
  `SHIPPING_CITY` VARCHAR(100) NOT NULL,
  `SHIPPING_STATE` VARCHAR(50) NOT NULL,
  `SHIPPING_COUNTRY` VARCHAR(100) NOT NULL,
  `DELIVERED` ENUM('YES','NO') DEFAULT 'NO',
  PRIMARY KEY (`ORDER_ID`),
  INDEX `PRODUCT_ID_idx` (`PRODUCT_ID`),
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID`),
  INDEX `PAYMENT_ID_idx` (`PAYMENT_ID`),
  CONSTRAINT `FK_PRODUCT`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `PRODUCT` (`PRODUCT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CUSTOMER`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PAYMENT`
    FOREIGN KEY (`PAYMENT_ID`)
    REFERENCES `PAYMENTS` (`PAYMENT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
